name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 拉取最新代码
        run: |
          cd /root/project
          git pull
      - name: 构建并部署
        run: |
          cd /root/project
          docker compose -f docker-compose-all.yml up -d --build
