name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 拉取最新代码
        run: |
          cd /root/project
          git pull
      - name: Docker 容器内构建前端
        run: |
          cd /root/project/admin-vue
          docker run --rm -v $(pwd):/app -w /app node:18 bash -c "npm install && npm run build"
      - name: 构建并部署
        run: |
          cd /root/project
          docker compose -f docker-compose-all.yml up -d --build
